### PR TITLE
.. i must be asleep

### PR DESCRIPTION
**Pull request by zeffii**

### CODE REVIEW

**Comment by zeffii** [comment]
@portnov  sorry :)

**Comment by zeffii** [comment]
actually, this doesn't seem to fix it either..

**Comment by zeffii** [comment]
new errors : )

**Comment by zeffii** [comment]
```
Traceback (most recent call last):
  File "C:\Users\zeffi\Downloads\blender29\2.93\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok-extra\__init__.py", line 78, in <module>
    imported_modules = [icons] + make_node_list()
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok-extra\__init__.py", line 74, in make_node_list
    module = importlib.import_module(f".{module_name}", base_name)
  File "C:\Users\zeffi\Downloads\blender29\2.93\python\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok-extra\nodes\curve\intersect_surface_plane.py", line 9, in <module>
    from sverchok.data_structure import updateNode, zip_long_repeat, match_long_repeat, ensure_nesting_level, throttle_and_update_node
ImportError: cannot import name 'throttle_and_update_node' from 'sverchok.data_structure' (C:\Users\zeffi\Desktop\scripts\addons_contrib\sverchok\data_structure.py)

```

**Comment by zeffii** [comment]
so these nodes need to drop importing `throttle_and_update_node`  and add `updateNode(self, context)`

```diff
-@throttle_and_update_node
def some_function(self, context):
    ... some code
+   updateNode(self, context)
```

and that's a little more involved to do agnostically?   

unless.. there was a `update_node` decorator :)

```diff
-@throttle_and_update_node
+@update_node
def some_function(self, context):
    ... some code
```

**Comment by zeffii** [comment]
@portnov  is it worth making the addon support both versions of the update-system?

**Comment by zeffii** [comment]
data_structure.py  `update_node`

```python
def process_node_after_function_completes(func):
    """
    use as a decorator
        class YourNode
            @update_node
            def mode_update(self, context):
                ...
    """
    @wraps(func)
    def wrapper_update(self, context):
        tree = self.id_data
        func(self, context)
        self.process_node(context)

    return wrapper_update
```

**Comment by zeffii** [comment]
or it could be part of sverchok-extra instead ..

**Comment by portnov** [comment]
@zeffii IMHO it's simpler to add a check into sverchok-extra: if sverchok is too old, give an error. I do not see a reason to support all possible combinations of versions.

Where exactly to add the check is the question...

**Comment by zeffii** [comment]
> I do not see a reason to support all possible combinations of versions.

yeah. settling on just 1.0.0 is OK then ?

**Comment by portnov** [comment]
ok

**Pull request merged**
