### PR TITLE
Basic Ladybug tools

### PR DESCRIPTION
**Pull request by vicdoval**
Really basic first implementation.
Two nodes:

Location
and Sun Position

image

### CODE REVIEW

**Comment by portnov** [comment]
Some thoughts
* Maybe it worth adding a special socket type for Location? If it is going to be used in other nodes. If it will be used only in these two, then SvStringSocket will do.
* Sunpath object can be probably output as a SvCurve object?

**Comment by Durman** [comment]
Also there is the date node.

**Comment by portnov** [comment]
Huh. We may end up with a "SvDateTime" socket type and a series of date-manipulation nodes :)

**Comment by vicdoval** [comment]
image
I don't know if me or someone else will be able to implement this tools in sverchok, but in that case it would not make sense to have a socket type for every different output this library offers....
Maybe a Ladybug socket for all of them.... (for the ones that are only to be accepted by another ladybug node)

**Comment by vicdoval** [comment]
> Sunpath object can be probably output as a SvCurve object?

I started that idea too but i felt it was better to create a Sun Path node for that task with some more options

**Comment by portnov** [comment]
@vicdoval do you think this should be merged as is or do you intend to change something before merging?

**Comment by vicdoval** [comment]
Is small step and probably the most interesting feature is being able to install ladybug tools with one click (to use it in SNL scripts) so... yes I guess it could be merge as it is and see if more interest/needs rises.

**Pull request merged**
