### PR TITLE
FreeCAD Solids

### PR DESCRIPTION
**Pull request by vicdoval**
Inspired in https://blenderartists.org/t/freecad-sverchok-subd-to-nurbs/1218702
Using FreeCAD as Python module a set of nodes to deal with solids

Installation
------------
A python 3 FreeCad is needed. a windows version can be found here https://github.com/sgrogan/FreeCAD/releases/tag/PY3.7-win
Then the path to the FreeCad `bin` folder has to be placed here
image
and click on "Set Path" and restart Blender

image

image

Still no documentation, just a staring point to show workflow

### CODE REVIEW

**Comment by vicdoval** [comment]
@portnov  To set a new Socket type do I have set it in directly in Sverchok?

**Comment by portnov** [comment]
@vicdoval no, you can implement it in Sverchok-Extra if you think it will not be usable outside of it.

**Comment by portnov** [comment]
@vicdoval do you intend to introduce new socket type in this PR or you would like this to be merged as-is?

**Comment by vicdoval** [comment]
I'm trying to move the whole module from sverchok-extra to sverchok extra-nodes but Im not sure if i will succeed, so lets wait a while before merging this commit..

**Comment by portnov** [comment]
Well, as far as I understand, your PR into Sverchok is in more actual state.

**Pull request closed without merging**
